[workspace]
authors = ["stream.liu <stream.iori97@gmail.com>"]
channels = ["conda-forge"]
name = "minimind"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
eval = "python eval_llm.py"
web = "cd scripts && streamlit run web_demo.py"
train-pretrain = "cd trainer && python train_pretrain.py"
train-sft = "python trainer/train_full_sft.py"
train-dpo = "python trainer/train_dpo.py"
train-lora = "python trainer/train_lora.py"
train-distill = "python trainer/train_distillation.py"
train-reason = "python trainer/train_distill_reason.py"
train-ppo = "python trainer/train_ppo.py"
train-grpo = "python trainer/train_grpo.py"
train-spo = "python trainer/train_spo.py"

[dependencies]
datasets = ">4.0.0"
datasketch = ">=1.8.0,<2"
flask = ">=3.1.2,<4"
flask-cors = ">=6.0.1,<7"
jieba = ">=0.42.1,<0.43"
jsonlines = ">=4.0.0,<5"
marshmallow = ">=4.1.1,<5"
matplotlib = ">=3.10.8,<4"
nltk = ">=3.9.2,<4"
numpy = ">=2.3.5,<3"
openai = ">=2.9.0,<3"
peft = ">=0.18.0,<0.19"
psutil = ">=7.1.3,<8"
pydantic = ">=2.12.5,<3"
rich = ">=13.0.0,<14"
scikit-learn = ">=1.7.2,<2"
sentence-transformers = ">=5.1.2,<6"
tiktoken = ">=0.12.0,<0.13"
transformers = ">=4.57.3,<5"
jinja2 = ">=3.1.6,<4"
ujson = ">=5.11.0,<6"
wandb = ">=0.23.1,<0.24"
streamlit = ">=1.52.1,<2"
einops = ">=0.8.1,<0.9"
pytorch = ">=2.9.1,<3"
torchvision = ">=0.24.1,<0.25"
trl = ">=0.25.1,<0.26"
pixi-pycharm = ">=0.0.10,<0.0.11"
addict = ">=2.4.0,<3"

[pypi-dependencies]
ngrok = ">=1.6.0, <2"
simhash = ">=2.1.2, <3"
swanlab = ">=0.6.11, <0.7"
modelscope = "==1.32.0"
